version: '3.8'

services:
  balancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2

  backend1:
    build: ./testing_servers/back1
    ports:
      - "8081:8081"

  backend2:
    build: ./testing_servers/back2
    ports:
      - "8082:8082"